Adding vsftp template
nytm/puppet-module-vsftpd pull request #2
Opened 2017-07-26 23:36 UTC by ramamaddodi

Added init.pp and vsftp template

Initial commit

Removed empty.conf.erb template

2017-07-27 16:15 UTC, ghoneycutt requested changes

2017-07-27 16:15 UTC, ghoneycutt commented on manifests/init.pp
> +  $nopriv_user             = 'ftpsecure',
for values that already exist, we should just set those in Hiera. We do want to submit this PR back to upstream.

2017-07-27 16:15 UTC, ghoneycutt commented on templates/empty.conf.erb
> -# This is vsftpd.conf created from scratch by puppet.
I don't see why this needs to be removed

2017-07-27 16:15 UTC, ghoneycutt commented on templates/vsftpd.conf.erb
> -<% if @anon_upload_enable == 'YES' -%>
why would this change?

2017-07-27 16:15 UTC, ghoneycutt commented on templates/vsftpd.conf.erb
> -<% if @anon_mkdir_write_enable == 'YES' -%>
why change?

2017-07-27 16:15 UTC, ghoneycutt commented on templates/vsftpd.conf.erb
> -<% else -%>
why change?

2017-07-27 16:15 UTC, ghoneycutt commented on templates/vsftpd.conf.erb
> -# Activate logging of uploads/downloads.
this comment should stay

2017-07-27 16:15 UTC, ghoneycutt commented on templates/vsftpd.conf.erb
> +#connect_from_port_20=<%= @connect_from_port_20 %>
instead of commenting out, this should be conditional

2017-07-27 16:15 UTC, ghoneycutt commented on templates/vsftpd.conf.erb
> +#chown_username=<%= @chown_uploads %>
make conditional

2017-07-27 16:15 UTC, ghoneycutt commented on templates/vsftpd.conf.erb
> -<% if @chown_username -%>
this should stay

2017-07-27 16:15 UTC, ghoneycutt commented on templates/vsftpd.conf.orig
> -#
before this is removed, ensure we have parity within our template

2017-07-27 20:24 UTC, ramamaddodi reviewed
Changes to template is as per current production template that we have for vsftp module

2017-07-27 20:24 UTC, ramamaddodi commented on manifests/init.pp
> +  $nopriv_user             = 'ftpsecure',
I will move this value to hiera

2017-07-27 20:24 UTC, ramamaddodi commented on templates/empty.conf.erb
> -# This is vsftpd.conf created from scratch by puppet.
Not sure why we need empty template when its not used

2017-07-27 20:24 UTC, ramamaddodi commented on templates/vsftpd.conf.erb
> -<% if @anon_upload_enable == 'YES' -%>
Mentioned change is according to what we have on current ftp/sftp production server.

2017-07-27 20:24 UTC, ramamaddodi commented on templates/vsftpd.conf.erb
> -<% if @anon_mkdir_write_enable == 'YES' -%>
Mentioned change is according to what we have on current ftp/sftp production server.

2017-07-27 20:24 UTC, ramamaddodi commented on templates/vsftpd.conf.orig
> -#
Our current template is according to our current production ftp/sftp config setting

2017-07-27 20:24 UTC, ramamaddodi commented on templates/vsftpd.conf.erb
> -<% if @chown_username -%>
Again mentioned changes are as per what we have on current production template for sftp/ftp environment.

2017-07-27 20:24 UTC, ramamaddodi commented on templates/vsftpd.conf.erb
> +#chown_username=<%= @chown_uploads %>
Again mentioned changes are as per what we have on current production template for sftp/ftp environment.

2017-07-27 20:24 UTC, ramamaddodi commented on templates/vsftpd.conf.erb
> +#connect_from_port_20=<%= @connect_from_port_20 %>
Again mentioned changes are as per what we have on current production template for sftp/ftp environment.

2017-07-27 20:24 UTC, ramamaddodi commented on templates/vsftpd.conf.erb
> -# Activate logging of uploads/downloads.
Mentioned changes are as per what we have on current production template for sftp/ftp environment.

2017-07-27 20:24 UTC, ramamaddodi commented on templates/vsftpd.conf.erb
> -<% else -%>
Mentioned changes are as per what we have on current production template for sftp/ftp environment.

2017-07-31 14:50 UTC, ghoneycutt requested changes

2017-07-31 14:50 UTC, ghoneycutt commented on manifests/init.pp
> +  $ls_recurse_enable       = 'YES',
we should not have changed the default value, instead should specify our value in hiera

2017-07-31 14:50 UTC, ghoneycutt commented on manifests/init.pp
> +  $setproctitle_enable     = undef,
same here with regards to defaults and using hiera. You can specify nil which should equate to undef like this

```yaml
vsftpd::setproctitle_enable: ~
```

2017-07-31 14:50 UTC, ghoneycutt commented on templates/vsftpd.conf.erb
> +#connect_from_port_20=<%= @connect_from_port_20 %>
do not comment out options, instead make them conditional. So if connect_from_port_20 is undef, then the configuration option is skipped.

2017-07-31 14:50 UTC, ghoneycutt commented on templates/vsftpd.conf.erb
> +chown_uploads=YES
this is just adding trailing whitespace

2017-08-01 00:38 UTC, closed without merging